import os

# MONGODB_HOST="mongodb://45.113.234.254:5020"
# ACCOUNT_HOST="http://localhost:3000"
# HISTORICAL_TRANSACTION_HOST="http://localhost:3000"

MONGODB_HOST=os.getenv("MONGODB_HOST")
ACCOUNT_HOST=os.getenv("ACCOUNT_HOST")
HISTORICAL_TRANSACTION_HOST=os.getenv("HISTORICAL_TRANSACTION_HOST")