
@host=http://localhost:3100

###
GET {{host}}/customer/?id_type=id_number&value=1605058497852873

###
GET {{host}}/customer/?id_type=cif_number&value=1681274973

###
POST {{host}}/customer/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password"
}

###
POST {{host}}/customer/logout
Content-Type: application/json

{
    "session_id" : "eyJjaWZfbnVtYmVyIjogIjE2ODEyNzQ5NzMiLCAiZGF0ZXRpbWUiOiAiMjAtMDItMjAyMiAwMjoyNTowOSIsICJ1dWlkIjogIjIwZjg2NGI4LTYzYTUtNGUzMi04MzUxLTEwZTRmY2ZlMmJmYiJ9"
}