version: "3.7"
services:
    monolith-app:
        build:
            context: ./
            dockerfile: ./app.Dockerfile
        container_name: monolith-app
        environment: 
            MONGODB_HOST: mongodb://45.113.235.79:3000
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
    nginx:
        build:
            context: ./nginx
            dockerfile: ./app.Dockerfile
        container_name: nginx
        ports:
            - "4000:80"