@host=http://localhost:7020

###
POST {{host}}/deposit HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "account_number": "8628312040",
  "amount": 1000
}

###
POST {{host}}/transfer HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "to_account_number": "7057815992",
  "from_account_number": "8628312040",
  "amount": 100
}