@customer_host=http://localhost:7000

###
POST {{customer_host}}/customer HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "User Name",
  "id_number": "31730059100009",
  "email": "user@gmail.com"
}

###
PUT {{customer_host}}/customer?cif_number=8063663495 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "User Name",
  "id_number": "31730059100009",
  "email": "user@gmail.com"
}

###
PUT {{customer_host}}/customer_user HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "username",
    "password": "password",
    "cif_number": "7358922550"
}

###
POST {{customer_host}}/customer/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "username",
    "password": "password"
}

###
GET {{customer_host}}/customers HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET {{customer_host}}/customer/cif?cif_number=5336293238 HTTP/1.1

###
GET {{customer_host}}/customer/id_number?id_number=31730059100009 HTTP/1.1

###
DELETE {{customer_host}}/customer/id_number?id_number=31730059100009 HTTP/1.1
Content-Type: application/json
Accept: application/json

###
DELETE {{customer_host}}/customer/cif?cif_number=5336293238 HTTP/1.1
Content-Type: application/json
Accept: application/json