@host=http://localhost:7040

###
POST {{host}}/bill/inquiry/tax
Content-Type: application/json
Accept: application/json

{
    "bill_id" : "001"
}

###
POST {{host}}/bill/payment/tax
Content-Type: application/json
Accept: application/json

{
    "bill_id" : "001",
    "account_number": "7273664125",
    "amount": 10
}