version: "3.7"
services:
    customer:
        build:
            context: ./customer
            dockerfile: ./app.Dockerfile
        container_name: customer
        # ports:
        #     - "3100:3100"
    account:
        build:
            context: ./account
            dockerfile: ./app.Dockerfile
        container_name: account
        # ports:
        #     - "3101:3101"
    transfer:
        build:
            context: ./transfer
            dockerfile: ./app.Dockerfile
        container_name: transfer
        # ports:
        #     - "3102:3102"
    payment:
        build:
            context: ./payment
            dockerfile: ./app.Dockerfile
        container_name: payment
        # ports:
        #     - "3103:3103"
    mq-sb-2:
        build:
            context: ./mq-sb-2
            dockerfile: ./app.Dockerfile
        container_name: mq-sb-2
    nginx:
        build:
            context: ./nginx
            dockerfile: ./app.Dockerfile
        container_name: nginx
        ports:
            - "4002:80"