version: "3.7"
services:
    customer:
        build:
            context: ./customer
            dockerfile: ./app.Dockerfile
        container_name: customer
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5000/
    account:
        build:
            context: ./account
            dockerfile: ./app.Dockerfile
        container_name: account
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5010/
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
    transfer:
        build:
            context: ./transfer
            dockerfile: ./app.Dockerfile
        container_name: transfer
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5020/
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
            ACCOUNT_HOST: http://account:3101
    payment:
        build:
            context: ./payment
            dockerfile: ./app.Dockerfile
        container_name: payment
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5030/
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
            ACCOUNT_HOST: http://account:3101
    nginx:
        build:
            context: ./nginx
            dockerfile: ./app.Dockerfile
        container_name: nginx
        ports:
            - "4003:80"