version: "3.7"
services:
    customer:
        build:
            context: ./customer
            dockerfile: ./app.Dockerfile
        container_name: customer
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5000/
    account:
        build:
            context: ./account
            dockerfile: ./app.Dockerfile
        container_name: account
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5010/
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
            RABBIT_MQ_HOST: 45.113.232.164:3020

            ROUTING_KEY_TO_TRANSFER: account_transfer
            ROUTING_KEY_TO_PAYMENT: account_payment
            ROUTING_KEY_TO_INTERBANK: account_transfer_interbank
            ROUTING_KEY_TO_REVERSAL_PAYMENT: account_reversal_payment
            ROUTING_KEY_TO_REVERSAL_INTERBANK_TRANSFER: account_reversal_interbank_transfer
    transfer:
        build:
            context: ./transfer
            dockerfile: ./app.Dockerfile
        container_name: transfer
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5020/
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
            RABBIT_MQ_HOST: 45.113.232.164:3020

            ROUTING_KEY_TO_ACCOUNT: transfer_account
            ROUTING_KEY_TO_ACCOUNT_DEBIT: transfer_account_debit
            ROUTING_KEY_TO_REVERSAL_INTERBANK: transfer_account_reversal
    payment:
        build:
            context: ./payment
            dockerfile: ./app.Dockerfile
        container_name: payment
        environment:
            MONGODB_HOST: mongodb://45.113.235.79:5020/
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
            RABBIT_MQ_HOST: 45.113.232.164:3020

            ROUTING_KEY_TO_ACCOUNT_DEBIT: payment_account_debit
            ROUTING_KEY_TO_REVERSAL_PAYMENT: payment_account_reversal
    mq-sb-1:
        build:
            context: ./mq-sb-1
            dockerfile: ./app.Dockerfile
        container_name: mq-sb-1
    nginx:
        build:
            context: ./nginx
            dockerfile: ./app.Dockerfile
        container_name: nginx
        ports:
            - "4001:80"