
@host=http://45.113.234.254:3000

###
GET {{host}}/customer/?id_type=id_number&value=1605058497852873
# response:
# HTTP/1.1 201 CREATED
# Server: nginx/1.21.6
# Date: Thu, 03 Mar 2022 03:42:36 GMT
# Content-Type: application/json
# Content-Length: 362
# Connection: close

# {
#   "cif_number": "1681274973",
#   "email": "user0@gmail.com",
#   "id_number": "1605058497852873",
#   "is_login": true,
#   "name": "User 0",
#   "password": "password",
#   "session_id": "eyJjaWZfbnVtYmVyIjogIjE2ODEyNzQ5NzMiLCAiZGF0ZXRpbWUiOiAiMDMtMDMtMjAyMiAwMzo0MjoxNyIsICJ1dWlkIjogIjQ2ODM3OWRkLTcyMGItNGIzNS1hOWVkLWY3MjY1ZjE4MjEwZiJ9",
#   "username": "user1"
# }


###
GET {{host}}/customer/?id_type=cif_number&value=1681274973
# response:
# HTTP/1.1 201 CREATED
# Server: nginx/1.21.6
# Date: Thu, 03 Mar 2022 03:42:48 GMT
# Content-Type: application/json
# Content-Length: 362
# Connection: close

# {
#   "cif_number": "1681274973",
#   "email": "user0@gmail.com",
#   "id_number": "1605058497852873",
#   "is_login": true,
#   "name": "User 0",
#   "password": "password",
#   "session_id": "eyJjaWZfbnVtYmVyIjogIjE2ODEyNzQ5NzMiLCAiZGF0ZXRpbWUiOiAiMDMtMDMtMjAyMiAwMzo0MjoxNyIsICJ1dWlkIjogIjQ2ODM3OWRkLTcyMGItNGIzNS1hOWVkLWY3MjY1ZjE4MjEwZiJ9",
#   "username": "user1"
# }


###
POST {{host}}/customer/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password"
}

# response:
# HTTP/1.1 200 OK
# Server: nginx/1.21.6
# Date: Thu, 03 Mar 2022 03:42:17 GMT
# Content-Type: application/json
# Content-Length: 425
# Connection: close

# {
#   "customer_data": {
#     "cif_number": "1681274973",
#     "email": "user0@gmail.com",
#     "id_number": "1605058497852873",
#     "is_login": false,
#     "name": "User 0",
#     "password": "password",
#     "session_id": "",
#     "username": "user1"
#   },
#   "session_id": "eyJjaWZfbnVtYmVyIjogIjE2ODEyNzQ5NzMiLCAiZGF0ZXRpbWUiOiAiMDMtMDMtMjAyMiAwMzo0MjoxNyIsICJ1dWlkIjogIjQ2ODM3OWRkLTcyMGItNGIzNS1hOWVkLWY3MjY1ZjE4MjEwZiJ9"
# }



###
POST {{host}}/customer/logout
Content-Type: application/json

{
    "session_id" : "eyJjaWZfbnVtYmVyIjogIjE2ODEyNzQ5NzMiLCAiZGF0ZXRpbWUiOiAiMDMtMDMtMjAyMiAwMzo0MTo0MCIsICJ1dWlkIjogIjViMGM0YzcxLWI0ZDQtNGRmYy1iMjQ1LTAzZGI3MzFjYjZmMiJ9"
}