version: "3.7"
services:
    customer:
        build:
            context: ./customer
            dockerfile: ./app.Dockerfile
        container_name: customer
        environment:
            MONGODB_READ_HOST: mongodb://45.113.235.79:6010/?readPreference=secondary&directConnection=true
            MONGODB_WRITE_HOST: mongodb://45.113.235.79:6000/?readPreference=primary&directConnection=true
    account:
        build:
            context: ./account
            dockerfile: ./app.Dockerfile
        container_name: account
        environment:
            MONGODB_READ_HOST=mongodb://192.168.1.137:6020/?readPreference=secondary&directConnection=true
            MONGODB_WRITE_HOST=mongodb://192.168.1.137:6000/?readPreference=primary&directConnection=true
    transfer:
        build:
            context: ./transfer
            dockerfile: ./app.Dockerfile
        container_name: transfer
        environment:
            MONGODB_READ_HOST: mongodb://45.113.235.79:6030/?readPreference=secondary&directConnection=true
            MONGODB_WRITE_HOST: mongodb://45.113.235.79:6000/?readPreference=primary&directConnection=true
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
    payment:
        build:
            context: ./payment
            dockerfile: ./app.Dockerfile
        container_name: payment
        environment:
            MONGODB_READ_HOST: mongodb://45.113.235.79:6040/?readPreference=secondary&directConnection=true
            MONGODB_WRITE_HOST: mongodb://45.113.235.79:6000/?readPreference=primary&directConnection=true
            SIM_INTERBANK_HOST: http://45.113.232.164:3000
            SIM_BILLPAYMENT_HOST: http://45.113.232.164:3010
    nginx:
        build:
            context: ./nginx
            dockerfile: ./app.Dockerfile
        container_name: nginx
        ports:
            - "4004:80"