@host=http://localhost:3103

###
GET {{host}}/payment/bill/inquiry?bill_id=553360290896

### normal: 553360290896; reversal: 999888777
POST {{host}}/payment/bill/payment
Content-Type: application/json

{
    "bill_id" : "553360290896",
    "account_number" : "0023418965",
    "biller_name" : "telkomsel",
    "amount" : 10,
    "cif_number" : "918382910",
    "description":  "TEST PAYMENT !",
    "biller_request_message" : {
        "bill_id" : "553360290896",
        "amount" : 10,
        "detail" : "0813-1600-6010",
        "description" : "TEST PAYMENT"
    }
}

###
GET {{host}}/payment/list?cif_number=918382910

###
GET {{host}}/payment/detail?transaction_id=7939292010