# @host = http://localhost:9010
@host = http://45.113.232.164:3010

###
POST {{host}}/create_billing
Content-Type: application/json

{
    "bill_name" : "telkomsel",
    "amount" : 450000
}

###
GET {{host}}/?bill_id=830090890024
Content-Type: application/json

###
POST {{host}}
Content-Type: application/json

{
    "bill_id" : "383276601961",
    "description" : "settlement success!"
}