import os

# RABBIT_MQ_HOST="45.113.232.164"
# RABBIT_MQ_PORT="3020"
# TRANSACTION_HOST="http://localhost:3020"
# HISTORICAL_TRANSACTION_HOST="http://localhost:3030"
# INTERBANK_HOST="http://localhost:3040"
# PAYMENT_HOST="http://localhost:3050"

RABBIT_MQ_HOST=os.getenv("RABBIT_MQ_HOST")
RABBIT_MQ_PORT=os.getenv("RABBIT_MQ_PORT")
TRANSACTION_HOST=os.getenv("TRANSACTION_HOST")
HISTORICAL_TRANSACTION_HOST=os.getenv("HISTORICAL_TRANSACTION_HOST")
INTERBANK_HOST=os.getenv("INTERBANK_HOST")
PAYMENT_HOST=os.getenv("PAYMENT_HOST")